### PR TITLE
Question bank functionality

### PR DESCRIPTION
**Pull request by dmols**
Added question bank functionality to the widget. CSS may need some adjusting but the QB works as intended. One thing to note is that the question bank dialog doesn't allow invalid entries in the input box, though there isn't an alert in place to tell the user to pick a valid number; open to suggestions on how to make the UI/UX for the dialog better.

### CODE REVIEW

**Review by cayb0rg — CHANGES_REQUESTED** [review]
Made my review for LCC before I saw this one, whoops. Everything works nicely, didn't have any issues with the randomization. Couldn't test the qset changes on local Materia since the old MWDK doesn't like installing widgets for me anymore, but they look good as well.

UI/UX: I appreciate that the dialog uses "yes" and "no" options, since that eliminates any confusion as to whether it's enabled. I think only the CSS needs to be adjusted like you said - maybe centering the options, changing colors to fit the theme, adding hover highlighting/cursor, etc.

**Review by cayb0rg — APPROVED** [review]
Greying-out the button on invalid inputs was a nice touch! Functionality here is great and the CSS changes look good.

I think using the same styling for the QB button as the questions would look nice, but that's completely up to you!
image

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
My feedback here is identical to what I provided for Last Chance Cadet: https://github.com/ucfopen/last-chance-cadet-materia-widget/pull/41#pullrequestreview-1839159215

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
Same feedback as Last Chance Cadet: you're making references in both the player and creator to properties attached to `qset.options`, but the `options` property may not exist. References to `qset.options.enableQuestionBank` etc should first make sure `qset.options` exists, or javascript will throw an error.

Once that's fixed, this should be good to go.

**Review by clpetersonucf — APPROVED** [review]
:+1:

**Pull request merged**
