### PR TITLE
Implemented keyboard and screen reader functionality

### PR DESCRIPTION
**Pull request by kywoodland**
I'm hoping to get some feedback on the functionality I've implemented so far so I can get a sense of how much I have left to do. I've been testing primarily with the keyboard Voice Over on mac, and will be using NVDA to test further on Windows. 

Known issues/things I'm still working on:
- Voice Over will sometimes get trapped inside of a list and cycle through it a few times before breaking out
- Currently, the aria-label for each word reflects what it's matched with (except on audio clue elements for now), but there is no immediate feedback when a match is first made. That's the next step
- Sometimes Voice Over cannot click on the Next/Previous page button unless it's tabbed backwards into it 
- I was trying to set it up so that when an element from one column is clicked, it auto focuses on the opposite column so a user doesn't have to tab through everything to get to it. I'm not sure if that's desired though as it might be confusing

### CODE REVIEW

**Comment by clpetersonucf** [comment]
Some thoughts on this so far! 

- The keyboard accessibility adds large outlines to certain elements - we could probably afford to disable though, and find a cleaner styling solution to better emphasize what element is currently selected with the keyboard. Increasing the contrast on hover states would be a good start.
- Voiceover seemed to handle most elements just fine. There isn't any sort of acknowledgement when an element is selected, deselected, or placed yet. Are you considering adding an `aria-live` region to make those sorts of state announcements?
- Tabbing through answer choices with audio controls is a little messy. It took multiple tries to find the right element to play the attached audio. Voiceover likes to talk over itself and ignore speaking important information (like playback duration), which made it frustrating.

Overall, it's certainly headed in the right direction! Personally, I'm OK with not moving the user's focus when an element is selected. It felt easy enough to tab to the opposite column and select a match manually.

**Comment by kywoodland** [comment]
Did some more things! Mostly responded to Corey's feedback + some other stuff:

- I removed the blue outline that appears on focus and increased color contrast on most elements to make that distinction stand out better. Also modified the colors a bit to fit the WCAG AA/AAA guidelines for Large Text. 
- I added a hidden aria-live element to live update when a match is made, which gives the user feedback "You have matched x with y." It's set to "assertive" and says this after the voice has finished reading the aria-label of the focused element. I looked into making it more immediate and found it might depend on user preferences, but I think it's good for now (I need to test it more though to make 100% sure it works in every case)
- I have hopefully fixed the audio control elements. Tabbing into it selects the word first, then another tab to focus on the player. Screen reader tells the user its match status and then lets them know there's an audio clue, along with its length. 

I'd like to say this is almost completely done, but of course there may be a few things I'm missing/forgetting. Plus, I still need to test it a bit more on NVDA and hopefully ChromeVox if I can.

**Comment by clpetersonucf** [comment]
This is looking really good! The only two things I've noticed:

- The aria-live region that announces when you've matched a pair speaks twice, at least with VoiceOver
- On single-page matching widgets, the Previous and Next buttons remain in the tab list and can be interacted with even when they're not visible and there are no pages to switch between. I only noticed because they're ahead of the Done button in the tab order.

Besides that, it's intuitive and easy to use! I think it's pretty close to ready.

**Comment by clpetersonucf** [comment]
The new update incorporates some of these changes and supercedes them - closing.

**Pull request closed without merging**
