### PR TITLE
Accessibility updates

### PR DESCRIPTION
**Pull request by clpetersonucf**
Includes:

- Full keyboard support, with a dedicated dialog modal for keyboard instructions in addition to reading instructions when focusing on the gameboard.
- Full screenreader support, including live regions for state updates

No fancy keyboard hotkeys with this one, besides using left and right arrow keys to quickly swap between question and answer columns.

Known issues:
- Selecting the play button on audio clues will also select the word associated with it, despite my best efforts to curtail the event propagation

### CODE REVIEW

**Comment by FrenjaminBanklin** [comment]
This is looking and feeling really good. The only things I can think of are extra and honestly pretty minor.

- I've been setting the aria-label of the keyboard instructions button to what the text contents of the keyboard instructions dialog would be to save unsighted users the hassle of actually opening the instructions up to see them.
- Unsighted users will find out pretty quick if the question/answer option they're on has audio in it, but it might not hurt to add that information to the aria-label too.
- I got stuck in a bit of a tug of war with the VO controls when trying to use the left and right arrow keys to move between the two columns, but it sorted itself out somehow. I'm wondering if specifically removing all but one of the elements in a question/answer element's DOM hierarchy would guaranteed avoid this or if it's just not worth worrying about.
- Using the right arrow key to jump forward a few seconds in an audio file works, but pressing the left arrow key will work exactly one time and then bubble up and move focus over to the question column. I imagine this would be the same but reversed for an audio element in the left column. This is probably the same problem you've already cited with using the Enter key to play audio also selecting the element.
- The audio cues when selecting a question/answer and then matching it are great, but it might be helpful to have a keybind that unsighted users can press to read out whatever their currently selected item is just in case they forget.

**Comment by cayb0rg** [comment]
Agree with Brandon's points. Additionally:
* There should be an audio indicator that all matches on a page are complete
* It could be helpful but not necessary to include in the aria-live update that a question/answer was unmatched if it got replaced with another question/answer

**Comment by clpetersonucf** [comment]
- Wrapped document selection methods in checks to allow tests to pass
- Appended the keyboard instructions to the keyboard instructions button via `aria-describedby` as requested
- Previous and Next buttons will now inform the user of how many matches are complete on the current page
- Appended note to `aria-label` on questions/answers with audio clues to let the user know as such

I think the VO controls + audio controls might be a Let It Ride situation. I haven't found a resolution that works.

> - There should be an audio indicator that all matches on a page are complete
> - It could be helpful but not necessary to include in the aria-live update that a question/answer was unmatched if it got replaced with another question/answer

I'm going to bundle these requests as resolved via the previous/next button informing the user of page status

> The audio cues when selecting a question/answer and then matching it are great, but it might be helpful to have a keybind that unsighted users can press to read out whatever their currently selected item is just in case they forget.

Might be over-engineering a bit, they can just tab forward and then backwards to re-read the aria-label text again

**Review by cayb0rg — APPROVED** [review]
Changes look god. Only suggestion I have is to focus the next unmatched question/answer when using the arrow keys to navigate to other column.

**Pull request merged**
